/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { InputType, Field } from "@nestjs/graphql";
import { ApiProperty } from "@nestjs/swagger";
import {
  IsString,
  MaxLength,
  IsOptional,
  ValidateNested,
} from "class-validator";
import { InvoiceCreateNestedManyWithoutCustomersInput } from "./InvoiceCreateNestedManyWithoutCustomersInput";
import { Type } from "class-transformer";
import { JobCardCreateNestedManyWithoutCustomersInput } from "./JobCardCreateNestedManyWithoutCustomersInput";
import { VehicleCreateNestedManyWithoutCustomersInput } from "./VehicleCreateNestedManyWithoutCustomersInput";

@InputType()
class CustomerCreateInput {
  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @MaxLength(1000)
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  address?: string | null;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  email?: string | null;

  @ApiProperty({
    required: false,
    type: () => InvoiceCreateNestedManyWithoutCustomersInput,
  })
  @ValidateNested()
  @Type(() => InvoiceCreateNestedManyWithoutCustomersInput)
  @IsOptional()
  @Field(() => InvoiceCreateNestedManyWithoutCustomersInput, {
    nullable: true,
  })
  invoices?: InvoiceCreateNestedManyWithoutCustomersInput;

  @ApiProperty({
    required: false,
    type: () => JobCardCreateNestedManyWithoutCustomersInput,
  })
  @ValidateNested()
  @Type(() => JobCardCreateNestedManyWithoutCustomersInput)
  @IsOptional()
  @Field(() => JobCardCreateNestedManyWithoutCustomersInput, {
    nullable: true,
  })
  jobCards?: JobCardCreateNestedManyWithoutCustomersInput;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @MaxLength(1000)
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  name?: string | null;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @MaxLength(1000)
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  phone?: string | null;

  @ApiProperty({
    required: false,
    type: () => VehicleCreateNestedManyWithoutCustomersInput,
  })
  @ValidateNested()
  @Type(() => VehicleCreateNestedManyWithoutCustomersInput)
  @IsOptional()
  @Field(() => VehicleCreateNestedManyWithoutCustomersInput, {
    nullable: true,
  })
  vehicles?: VehicleCreateNestedManyWithoutCustomersInput;
}

export { CustomerCreateInput as CustomerCreateInput };
