/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { PrismaService } from "../../prisma/prisma.service";

import {
  Prisma,
  JobCard as PrismaJobCard,
  Invoice as PrismaInvoice,
  Service as PrismaService,
  Customer as PrismaCustomer,
} from "@prisma/client";

export class JobCardServiceBase {
  constructor(protected readonly prisma: PrismaService) {}

  async count(args: Omit<Prisma.JobCardCountArgs, "select">): Promise<number> {
    return this.prisma.jobCard.count(args);
  }

  async jobCards(args: Prisma.JobCardFindManyArgs): Promise<PrismaJobCard[]> {
    return this.prisma.jobCard.findMany(args);
  }
  async jobCard(
    args: Prisma.JobCardFindUniqueArgs
  ): Promise<PrismaJobCard | null> {
    return this.prisma.jobCard.findUnique(args);
  }
  async createJobCard(args: Prisma.JobCardCreateArgs): Promise<PrismaJobCard> {
    return this.prisma.jobCard.create(args);
  }
  async updateJobCard(args: Prisma.JobCardUpdateArgs): Promise<PrismaJobCard> {
    return this.prisma.jobCard.update(args);
  }
  async deleteJobCard(args: Prisma.JobCardDeleteArgs): Promise<PrismaJobCard> {
    return this.prisma.jobCard.delete(args);
  }

  async findInvoices(
    parentId: string,
    args: Prisma.InvoiceFindManyArgs
  ): Promise<PrismaInvoice[]> {
    return this.prisma.jobCard
      .findUniqueOrThrow({
        where: { id: parentId },
      })
      .invoices(args);
  }

  async findServices(
    parentId: string,
    args: Prisma.ServiceFindManyArgs
  ): Promise<PrismaService[]> {
    return this.prisma.jobCard
      .findUniqueOrThrow({
        where: { id: parentId },
      })
      .services(args);
  }

  async getCustomer(parentId: string): Promise<PrismaCustomer | null> {
    return this.prisma.jobCard
      .findUnique({
        where: { id: parentId },
      })
      .customer();
  }
}
